version: "3"

services:
  backend:
    image: node:18.17.1
    container_name: backend
    volumes:
      - ./backend:/backend
    ports:
      - 3333:3333
    env_file:
      - .env

    command: bash -c "cd /backend && yarn install && yarn start"

  frontend:
    image: node:18.17.1
    container_name: frontend
    volumes:
      - ./frontend:/frontend
    ports:
      - 80:80
    depends_on:
      - backend
    command: bash -c "cd /frontend && yarn install && yarn dev"

  mosquitto:
    image: eclipse-mosquitto:2.0.17
    container_name: mosquitto
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    ports:
      - 1883:1883
      - 9001:9001

  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    restart: on-failure:10
    volumes:
      - influxdb_data:/var/lib/influxdb:rw
    ports:
      - ${DOCKER_INFLUXDB_INIT_PORT}:8086    
    env_file:
      - .env
    entrypoint: [ "./entrypoint.sh" ]

  telegraf:
    image: telegraf:1.25
    container_name: telegraf
    restart: unless-stopped
    volumes:
      - ${TELEGRAF_CFG_PATH}:/etc/telegraf/telegraf.conf:rw
    env_file:
      - .env
    depends_on:
      - influxdb

  grafana:
    image: grafana/grafana-oss:8.4.3
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana:rw
    ports:
      - ${GRAFANA_PORT}:3000 
    depends_on:
      - influxdb

volumes:
  influxdb_data:
  grafana_data:
